

# Monitor config
monitor=,preferred,auto,auto

# Keyboard Config

# Execute startup applications
exec-once waybar
#exec-once hyprpaper

# source a config file
#source = ~/.config/hypr/...

# Set default applications
$terminal = kitty
$fileManager = dolphin
$menu = rofi --show drun

# default env vars
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if have that

# input configuration
input {
	kb_layout = de
	kb_variant =
	kb_model =
	kb_options =
	kb_rules =

	follow_mouse = 1

	touchpad {
		natural_scroll = true
	}

	sensitivity = 0 # from -1,0 until 1.0, 0 means no modifiaction
}

# general config (see configuring/variables)
general {
	gaps_in = 5
	gaps_out = 5
	border_size = 2
	col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
	col.inactive_border = rgba(595959aa)

	layout = dwindle

	#see configuration/tearing before turning on:
	allow_tearing =false
}

decoration {
	rounding = 10

	blur {
		enabled = true
		size = 3
		passes = 1

		vibrancy = 0.1696
	}

	drop_shadow = true
	shadow_range = 4
	shadow_render_power = 3
	col.shadow = rgba(1a1a1aee)

}

animations {
	enabled = true

}
